<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150201/1-150201195146.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/150201/1-150201195146.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="652";
$z[1][4]['height']="368";

?>