<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150105/1-150105221T4.jpg ",93,244);
$z[1][4]['ddimg']="/uploads/allimg/150105/1-150105221T4.jpg";
$z[1][4]['text']="Ïû·À³µ";
$z[1][4]['width']="450";
$z[1][4]['height']="600";

?>