<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150105/1-150105221K9.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/150105/1-150105221K9.jpg";
$z[1][4]['text']="4╤╟ве╩П";
$z[1][4]['width']="488";
$z[1][4]['height']="550";

?>