<field:videolist itemname="视频列表" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:videolist>
<field:plot itemname="剧情介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plot>
<field:players itemname="播放器类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:players>
<field:language itemname="视频语言" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:language>
<field:softrank itemname="视频等级" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:softrank>