<?php
$z[0]=Array("field","</b></div>\n    <{dede:channelartlist}\n     <dl class=\"tbox\"><dt><strong><a href=\"{dede:field name='typeurl'",23,160);
$z[0][4]['name']="typename";
$z[1]=Array("field","",167,264);
$z[1][4]['name']="typename";
$z[1][4]['/</a></strong><span class']="more";
$z[1][4]['><a href']="{dede:field name='typeurl'";
$z[2]=Array("arclist","\n    <li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>",318,500);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";

?>