<channel:id>7</channel:id>
<channel:nid>video</channel:nid>
<channel:typename>视频</channel:typename>
<channel:maintable>#@__archives</channel:maintable>
<channel:addtable>#@__addonvideo</channel:addtable>
<channel:addcon>video_add.php</channel:addcon>
<channel:mancon>content_list.php</channel:mancon>
<channel:editcon>video_edit.php</channel:editcon>
<channel:useraddcon>video_add.php</channel:useraddcon>
<channel:usermancon>video_list.php</channel:usermancon>
<channel:usereditcon>video_edit.php</channel:usereditcon>
<channel:fieldset>
<field:videolist itemname="视频列表" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:videolist>
<field:plot itemname="剧情介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plot>
<field:players itemname="播放器类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:players>
<field:language itemname="视频语言" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:language>
<field:softrank itemname="视频等级" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:softrank>
</channel:fieldset>
<channel:listfields>videolist,plot,players,language,softrank</channel:listfields>
<channel:allfields></channel:allfields>
<channel:issystem>0</channel:issystem>
<channel:isshow>1</channel:isshow>
<channel:issend>1</channel:issend>
<channel:arcsta>-1</channel:arcsta>
<channel:usertype></channel:usertype>
<channel:sendrank>0</channel:sendrank>
<channel:isdefault>0</channel:isdefault>
<channel:needdes>1</channel:needdes>
<channel:needpic>1</channel:needpic>
<channel:titlename>标题</channel:titlename>
<channel:onlyone>0</channel:onlyone>
<channel:dfcid>0</channel:dfcid>
