<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,364);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,455);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",655,690);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n	  	   <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n         ",862,1012);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4,5,6,7,8,9,10,11,12,13";
$z[6]=Array("field","",1438,1457);
$z[6][4]['name']="title";
$z[7]=Array("field","",1498,1527);
$z[7][4]['name']="position";
$z[8]=Array("field","",1687,1706);
$z[8][4]['name']="title";
$z[9]=Array("field","",1746,1766);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1773,1829);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",1851,1869);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",1905,1930);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",1946,1972);
$z[13][4]['get']="next";
$z[14]=Array("include","",2192,2229);
$z[14][4]['filename']="footer.htm";

?>