<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,364);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,455);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",653,688);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n	  	   <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",859,1008);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4,5,6,7,8,9,10,11,12,13";
$z[6]=Array("field","",1434,1453);
$z[6][4]['name']="title";
$z[7]=Array("field","",1494,1523);
$z[7][4]['name']="position";
$z[8]=Array("field","",1681,1700);
$z[8][4]['name']="title";
$z[9]=Array("field","",1740,1760);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1767,1823);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",1845,1863);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",1899,1924);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",1940,1966);
$z[13][4]['get']="next";
$z[14]=Array("include","",2181,2218);
$z[14][4]['filename']="footer.htm";

?>