<?php
$z[0]=Array("arclist","\r\n						<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]...</a></li>\r\n						",182,359);
$z[0][4]['orderby']="id";
$z[0][4]['limit']="0,5";
$z[0][4]['titlelen']="30";
$z[0][4]['typeid']="top";
$z[1]=Array("type","\r\n				<span id=\"head_right\"><a href=\"[field:typeurl /]\">MORE+</a></span>\r\n				",510,623);
$z[1][4]['typeid']="43";
$z[2]=Array("arclist","\r\n						<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:image/]</a></li>\r\n						",683,868);
$z[2][4]['row']="4";
$z[2][4]['typeid']="43";
$z[2][4]['type']="commend";
$z[2][4]['imgwidth']="120";
$z[2][4]['imgheight']="120";

?>