<?php
$z[0]=Array("field","",251,270);
$z[0][4]['name']="title";
$z[1]=Array("global","",271,297);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,359);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",398,449);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",642,677);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",776,798);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\n	  	   <li><a  href='[field:typeurl/]'>[field:typename /]</a></li>\n      ",828,942);
$z[6][4]['type']="son";
$z[7]=Array("field","",1099,1118);
$z[7][4]['name']="title";
$z[8]=Array("field","",1159,1188);
$z[8][4]['name']="position";
$z[9]=Array("field","",1342,1361);
$z[9][4]['name']="title";
$z[10]=Array("field","",1400,1420);
$z[10][4]['name']="writer";
$z[11]=Array("field","",1427,1483);
$z[11][4]['name']="pubdate";
$z[11][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[12]=Array("field","",1502,1520);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",1554,1579);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",1593,1619);
$z[14][4]['get']="next";
$z[15]=Array("include","",1827,1864);
$z[15][4]['filename']="footer.htm";

?>