<?php
$z[0]=Array("field","",251,270);
$z[0][4]['name']="title";
$z[1]=Array("global","",271,297);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,359);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",398,449);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",641,676);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n	  	   <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\n        ",841,988);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4,5,6,7,8,9,10,11,12,13";
$z[6]=Array("field","",1145,1164);
$z[6][4]['name']="title";
$z[7]=Array("field","",1205,1234);
$z[7][4]['name']="position";
$z[8]=Array("field","",1387,1406);
$z[8][4]['name']="title";
$z[9]=Array("field","",1445,1465);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1472,1528);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",1547,1565);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",1599,1624);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",1638,1664);
$z[13][4]['get']="next";
$z[14]=Array("include","",1868,1905);
$z[14][4]['filename']="footer.htm";

?>