<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150131/1-150131232634.jpg ",93,257);
$z[1][4]['ddimg']="/uploads/allimg/150131/1-150131232634.jpg";
$z[1][4]['text']="本人 帅死人不偿命";
$z[1][4]['width']="650";
$z[1][4]['height']="731";

?>