<?php
$z[0]=Array("field","",38,66);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",69,166);
$z[1][4]['name']="typename";
$z[1][4]['/</a></strong><span class']="more";
$z[1][4]['><a href']="{dede:field name='typeurl'";
$z[2]=Array("arclist","\n<li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>",216,394);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";

?>