<DIV class=box><A class=imgBorder href="[field:arcurl/]" target=_blank>[field:image/]</A> <P><A href="[field:arcurl/]" target=_blank>[field:title/]</A></P>
	</DIV>

<!-- 图片列表 end --></DIV>
<DIV class=RightBotton id=RightArr></DIV></DIV>
<SCRIPT language=javascript type=text/javascript>
		<!--//--><![CDATA[//><!--
		var scrollPic_02 = new ScrollPic();
		scrollPic_02.scrollContId   = "ISL_Cont_1";
		scrollPic_02.arrLeftId      = "LeftArr";//左箭头ID
		scrollPic_02.arrRightId     = "RightArr"; //右箭头ID
		scrollPic_02.frameWidth     = 908;//显示框宽度
		scrollPic_02.pageWidth      = 160; //翻页宽度
		scrollPic_02.speed          = 50; //移动速度(毫秒，越小越快)
		scrollPic_02.space          = 10; //每次移动像素(单位px，越大越快)
		scrollPic_02.autoPlay       = true; //自动播放
		scrollPic_02.autoPlayTime   = 3; //自动播放间隔时间(秒)
		scrollPic_02.initialize(); //初始化
		//--><!]]>
	</SCRIPT>
	</DIV>
	<!--滚动图片 end-->
					
		</div>
  	</div><!--content end-->
	
{dede:include filename="footer.html"