<?php
$z[0]=Array("global","",117,142);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",155,181);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("type","\r\n				<li><a href=\"[field:typeurl /]\">给我留言<img src=\"[field:global.cfg_cmspath/]/templets/default/images/messages.png\"  width=\"20px\" height=\"20px\"/></a></li>\r\n				",665,866);
$z[2][4]['typeid']="47";
$z[3]=Array("type","\r\n				<li><a href=\"[field:typeurl /]\">故事-STORY</a></li>\r\n				",1002,1100);
$z[3][4]['typeid']="42";
$z[4]=Array("type","\r\n				<li><a href=\"[field:typeurl /]\">相册-PHOTO</a></li>\r\n				",1106,1204);
$z[4][4]['typeid']="43";
$z[5]=Array("type","\r\n				<li><a href=\"[field:typeurl /]\">视频-VIDEO</a></li>\r\n				",1210,1308);
$z[5][4]['typeid']="44";
$z[6]=Array("type","\r\n				<li><a href=\"[field:typeurl /]\">关于-ABOUT</a></li>\r\n				",1314,1412);
$z[6][4]['typeid']="45";

?>