<?php
$z[0]=Array("global","",91,117);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",226,251);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",1149,1174);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\n      <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\n      ",1197,1319);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[4]=Array("global","",1543,1568);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channelartlist","\n          <li> <a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\n            <ul style=\"border:none;\">\n              {dede:channel type='son' noself='yes'}\n              <li> <a href=\"[field:typelink /]\">[field:typename/]</a> </li>\n              {/dede:channel}\n            </ul>\n          </li>\n          ",1595,2010);
$z[5][4]['typeid']="1,14,15,17,25,29,30";
$z[6]=Array("global","",2348,2374);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("global","",2494,2520);
$z[7][4]['name']="cfg_cmspath";
$z[8]=Array("global","",2758,2784);
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("global","",2927,2953);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("global","",3100,3126);
$z[10][4]['name']="cfg_cmspath";

?>