<?php
$z[0]=Array("type","\r\n			<a href=\"[field:typeurl /]\">3D相册</a>\r\n		",150,232);
$z[0][4]['typeid']="48";
$z[1]=Array("type","\r\n			<a href=\"[field:typeurl /]\">留言墙</a>\r\n		",276,358);
$z[1][4]['typeid']="47";
$z[2]=Array("global","",439,465);
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",694,719);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",918,943);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("type","\r\n			<li id=\"STORY\" onmouseover=\"mover_STORY()\" onmouseout=\"mout_STORY()\"  class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">故事</div><div class=\"li-a2\">STORY</div></a></li>\r\n			",1021,1250);
$z[5][4]['typeid']="42";
$z[6]=Array("type","\r\n			<li id=\"PHOTO\" onmouseover=\"mover_PHOTO()\" onmouseout=\"mout_PHOTO()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">相册</div><div class=\"li-a2\">PHOTO </div></a></li>\r\n			",1255,1484);
$z[6][4]['typeid']="43";
$z[7]=Array("type","\r\n			<li id=\"VIDEO\" onmouseover=\"mover_VIDEO()\" onmouseout=\"mout_VIDEO()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">视频</div><div class=\"li-a2\">VIDEO</div></a></li>\r\n			",1489,1717);
$z[7][4]['typeid']="44";
$z[8]=Array("type","\r\n			<li id=\"ABOUT\" onmouseover=\"mover_ABOUT()\" onmouseout=\"mout_ABOUT()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">关于</div><div class=\"li-a2\">ABOUT</div></a></li>\r\n		    ",1722,1953);
$z[8][4]['typeid']="45";

?>