<?php
$z[0]=Array("type","\r\n			<a href=\"[field:typeurl /]\" title=\"进入3D相册\">3D相册</a>\r\n		",150,251);
$z[0][4]['typeid']="48";
$z[1]=Array("type","\r\n			<a href=\"[field:typeurl /]\" title=\"进入留言墙\">留言墙</a>\r\n		",295,396);
$z[1][4]['typeid']="47";
$z[2]=Array("global","",477,503);
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",732,757);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",968,993);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("type","\r\n			<li id=\"STORY\" onmouseover=\"mover_STORY()\" onmouseout=\"mout_STORY()\"  class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">故事</div><div class=\"li-a2\">STORY</div></a></li>\r\n			",1071,1300);
$z[5][4]['typeid']="49";
$z[6]=Array("type","\r\n			<li id=\"PHOTO\" onmouseover=\"mover_PHOTO()\" onmouseout=\"mout_PHOTO()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">相册</div><div class=\"li-a2\">PHOTO </div></a></li>\r\n			",1305,1534);
$z[6][4]['typeid']="43";
$z[7]=Array("type","\r\n			<li id=\"VIDEO\" onmouseover=\"mover_VIDEO()\" onmouseout=\"mout_VIDEO()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">视频</div><div class=\"li-a2\">VIDEO</div></a></li>\r\n			",1539,1767);
$z[7][4]['typeid']="44";
$z[8]=Array("type","\r\n			<li id=\"ABOUT\" onmouseover=\"mover_ABOUT()\" onmouseout=\"mout_ABOUT()\" class=\"button dh\"><a href=\"[field:typeurl /]\"><div class=\"li-a1\">关于</div><div class=\"li-a2\">ABOUT</div></a></li>\r\n		    ",1772,2003);
$z[8][4]['typeid']="45";

?>