<?php
$z[0]=Array("global","",91,117);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",226,251);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",1150,1175);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\n      <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\n      ",1198,1320);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[4]=Array("global","",1507,1532);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channelartlist","\n      <li> <a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\n        <ul style=\"border:none;\">\n          {dede:channel type='son' noself='yes'}\n          <li> <a href=\"[field:typelink /]\">[field:typename/]</a> </li>\n          {/dede:channel}\n        </ul>\n      </li>\n      ",1555,1938);
$z[5][4]['typeid']="1,14,15,17,25,29,30";
$z[6]=Array("global","",2261,2287);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("global","",2407,2433);
$z[7][4]['name']="cfg_cmspath";

?>