<?php
$z[0]=Array("global","",586,612);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",768,794);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",910,936);
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",1057,1083);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("global","",1479,1504);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n      <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1528,1652);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[6]=Array("global","",1883,1908);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",2519,2544);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("channelartlist","\r\n          <li> <a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\r\n            <ul style=\"border:none;\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li> <a href=\"[field:typelink /]\">[field:typename/]</a> </li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2572,2995);
$z[8][4]['typeid']="1,14,15,17,25,29,30";
$z[9]=Array("global","",3347,3373);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("global","",3494,3520);
$z[10][4]['name']="cfg_cmspath";

?>