<?php
$z[0]=Array("field","",251,270);
$z[0][4]['name']="title";
$z[1]=Array("global","",271,297);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,366);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",405,463);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n	  	   <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\n         ",1030,1178);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4,5,6,7,8,9,10,11,12,13";
$z[6]=Array("field","",1336,1359);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1400,1429);
$z[7][4]['name']="position";
$z[8]=Array("list","\n	     <li><a  href=\"[field:arcurl/]\" >[field:image/][field:title/]</a></li>\n	    ",1602,1766);
$z[8][4]['pagesize']="9";
$z[8][4]['type']="image.";
$z[8][4]['imgwidth']="196";
$z[8][4]['imgheight']="196";
$z[9]=Array("pagelist","",1858,1920);
$z[9][4]['listitem']="index,end,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2077,2114);
$z[10][4]['filename']="footer.htm";

?>