<?php
$z[0]=Array("field","",251,270);
$z[0][4]['name']="title";
$z[1]=Array("global","",271,297);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,366);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",405,463);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",962,984);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\n	  	   <li><a  href='[field:typeurl/]'>[field:typename /]</a></li>\n      ",1014,1128);
$z[6][4]['type']="son";
$z[7]=Array("field","",1285,1308);
$z[7][4]['name']="typename";
$z[8]=Array("field","",1349,1378);
$z[8][4]['name']="position";
$z[9]=Array("list","\n      <li><span>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n    ",1552,1713);
$z[9][4]['pagesize']="10";
$z[10]=Array("pagelist","",1753,1815);
$z[10][4]['listitem']="index,end,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",1935,1972);
$z[11][4]['filename']="footer.htm";

?>