<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",842,877);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n	  	   <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1047,1194);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4,5,6,7,8,9,10,11,12,13";
$z[6]=Array("field","",1613,1636);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1677,1706);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n      <li><span>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",1885,2048);
$z[8][4]['pagesize']="10";
$z[9]=Array("pagelist","",2093,2155);
$z[9][4]['listitem']="index,end,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2282,2319);
$z[10][4]['filename']="footer.htm";

?>