<?php
$z[0]=Array("global","",222,248);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",249,268);
$z[1][4]['name']="title";
$z[2]=Array("field","",309,336);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",376,430);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",474,500);
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",10306,10332);
$z[5][4]['name']="cfg_cmspath";

?>